import staff1 from '../static/staff/staff1.svg'
import staff2 from '../static/staff/staff2.svg'
import staff3 from '../static/staff/staff3.svg'
import staff4 from '../static/staff/staff4.svg'
import staff5 from '../static/staff/staff5.svg'
import staff6 from '../static/staff/staff6.svg'
import staff7 from '../static/staff/staff7.svg'
import staff8 from '../static/staff/staff8.svg'
import staff9 from '../static/staff/staff9.svg'
import staff10 from '../static/staff/staff10.svg'
import staff11 from '../static/staff/staff11.svg'
import staff12 from '../static/staff/staff12.svg'

export const staff = [
    [
        {
            id: '1',
            name: 'Алексей Щербаков',
            position: 'UI/UX дизайнер',
            workplace: 'Отдел разработки мобильного приложения',
            img: staff1,
            status: 'priority',
            num: 3,
            doc: 255,
        },
        {
            id: '2',
            name: 'Floyd Miles',
            position: 'Маркетолог',
            workplace: 'Отдел разработки мобильного приложения',
            img: staff2,
            status: 'priority',
            num: 2,
            doc: 182,
        },
        {
            id: '3',
            name: 'Theresa Webb',
            position: 'Менеджер по продажам',
            workplace: 'Отдел продаж',
            img: staff3,
            status: 'priority',
            num: 3,
            doc: 255,
        },
        {
            id: '4',
            name: 'Vanessa Johnson',
            position: 'UI/UX дизайнер',
            workplace: 'Отдел разработки мобильного приложения',
            img: staff4,
            status: 'priority',
            num: 3,
            doc: 182,
        },
    ],
    [
        {
            id: '5',
            name: 'Kristin Watson',
            position: 'PHP Developer',
            workplace: 'Housekeepers',
            img: staff5,
            status: 'priority',
            num: 3,
            doc: 182,
        },
        {
            id: '6',
            name: 'Jacob Jones',
            position: 'Freshers',
            workplace: 'Finance',
            img: staff6,
            status: 'secondary',
            num: 3,
            doc: 182,
        },
        {
            id: '7',
            name: 'Wade Warren',
            position: 'UI/UX дизайнер',
            workplace: 'Management',
            img: staff7,
            status: 'priority',
            num: 3,
            doc: 182,
        },
        {
            id: '8',
            name: 'Cameron Williamson',
            position: 'Joomla Developer',
            workplace: 'Accounting',
            img: staff8,
            status: 'secondary',
            num: 3,
            doc: 182,
        },
        {
            id: '9',
            name: 'Devon Lane',
            position: 'Python Developer',
            workplace: 'Laundry',
            img: staff9,
            status: 'priority',
            num: 3,
            doc: 182,
        },
        {
            id: '10',
            name: 'Jacob Jones',
            position: 'Freshers',
            workplace: 'Finance',
            img: staff6,
            status: 'secondary',
            num: 3,
            doc: 182,
        },
    ],
    [],
    [
        {
            id: '11',
            name: 'Guy Hawkins',
            position: 'UX Architect',
            workplace: 'Housekeeping management',
            img: staff10,
            status: 'priority',
            num: 3,
            doc: 182,
        },
        {
            id: '12',
            name: 'Annette Black',
            position: 'Human Resource',
            workplace: 'Operations',
            img: staff11,
            status: 'urgent',
            num: 2,
            doc: 182,
        },
        {
            id: '13',
            name: 'Esther Howard',
            position: 'Python Developer',
            workplace: 'Restaurant Management',
            img: staff12,
            status: 'urgent',
            num: 3,
            doc: 255,
        },
    ],
    [
        {
            id: '14',
            name: 'Алексей Щербаков',
            position: 'UI/UX дизайнер',
            workplace: 'Отдел разработки мобильного приложения',
            img: staff1,
            status: 'priority',
            num: 3,
            doc: 255,
        },
        {
            id: '15',
            name: 'Алексей Щербаков',
            position: 'UI/UX дизайнер',
            workplace: 'Отдел разработки мобильного приложения',
            img: staff1,
            status: 'priority',
            num: 3,
            doc: 255,
        },
        {
            id: '16',
            name: 'Алексей Щербаков',
            position: 'UI/UX дизайнер',
            workplace: 'Отдел разработки мобильного приложения',
            img: staff1,
            status: 'priority',
            num: 3,
            doc: 255,
        },
        {
            id: '17',
            name: 'Алексей Щербаков',
            position: 'UI/UX дизайнер',
            workplace: 'Отдел разработки мобильного приложения',
            img: staff1,
            status: 'priority',
            num: 3,
            doc: 255,
        },
        {
            id: '18',
            name: 'Алексей Щербаков',
            position: 'UI/UX дизайнер',
            workplace: 'Отдел разработки мобильного приложения',
            img: staff1,
            status: 'priority',
            num: 3,
            doc: 255,
        },
    ],
]
